export type {
  TFn,
  SuggestionStatus,
  PriceSuggestion,
  NewSuggestionInput,
} from "./types";
export { SUGGESTION_STATUS, SUGGESTION_STATUS_KEYS, PRICE_TOLERANCE } from "./types";

import type { PriceSuggestion } from "./types";

export const SEED_SUGGESTIONS: PriceSuggestion[] = [
  {
    id: "ps-1",
    storeId: "store-1",
    storeName: "Bab Ezzouar Market",
    productId: "prod-1",
    productName: "Coca-Cola 1L",
    productCategory: "Drinks",
    barcode: "6131234567890",
    blinkPrice: 110,
    currentPrice: 120,
    suggestedPrice: 115,
    status: "pending",
    deviation: 4.5,
    submittedAt: Date.now() - 3600000,
  },
  {
    id: "ps-2",
    storeId: "store-1",
    storeName: "Bab Ezzouar Market",
    productId: "prod-2",
    productName: "Pain Tradition",
    productCategory: "Food",
    barcode: "6131234567891",
    blinkPrice: 25,
    currentPrice: 30,
    suggestedPrice: 28,
    status: "pending",
    deviation: 12,
    submittedAt: Date.now() - 7200000,
  },
  {
    id: "ps-3",
    storeId: "store-2",
    storeName: "Hydra Express",
    productId: "prod-3",
    productName: "Lait Candia 1L",
    productCategory: "Dairy",
    barcode: "6131234567892",
    blinkPrice: 85,
    currentPrice: 90,
    suggestedPrice: 88,
    status: "accepted",
    deviation: 3.5,
    submittedAt: Date.now() - 86400000,
    reviewedAt: Date.now() - 43200000,
    reviewedBy: "admin@blink.dz",
  },
  {
    id: "ps-4",
    storeId: "store-3",
    storeName: "Kouba Superette",
    productId: "prod-4",
    productName: "Huile Elio 5L",
    productCategory: "Food",
    barcode: "6131234567893",
    blinkPrice: 900,
    currentPrice: 980,
    suggestedPrice: 950,
    status: "pending",
    deviation: 5.6,
    submittedAt: Date.now() - 14400000,
  },
  {
    id: "ps-5",
    storeId: "store-4",
    storeName: "Oran Centre",
    productId: "prod-5",
    productName: "Creme Maison 500g",
    productCategory: "Dairy",
    barcode: "6131234567894",
    blinkPrice: 200,
    currentPrice: 200,
    suggestedPrice: 260,
    status: "rejected",
    deviation: 30,
    submittedAt: Date.now() - 172800000,
    reviewedAt: Date.now() - 86400000,
    reviewedBy: "admin@blink.dz",
    note: "Exceeds 20% tolerance",
  },
  {
    id: "ps-6",
    storeId: "store-2",
    storeName: "Hydra Express",
    productId: "prod-6",
    productName: "Pepsi 2L",
    productCategory: "Drinks",
    barcode: "6131234567895",
    blinkPrice: 150,
    currentPrice: 160,
    suggestedPrice: 155,
    status: "accepted",
    deviation: 3.3,
    submittedAt: Date.now() - 259200000,
    reviewedAt: Date.now() - 172800000,
    reviewedBy: "admin@blink.dz",
  },
  {
    id: "ps-7",
    storeId: "store-5",
    storeName: "Constantine Market",
    productId: "prod-7",
    productName: "Yaourt Danone x12",
    productCategory: "Dairy",
    barcode: "6131234567896",
    blinkPrice: 480,
    currentPrice: 500,
    suggestedPrice: 520,
    status: "pending",
    deviation: 8.3,
    submittedAt: Date.now() - 1800000,
  },
  {
    id: "ps-8",
    storeId: "store-1",
    storeName: "Bab Ezzouar Market",
    productId: "prod-8",
    productName: "Eau Ifri 1.5L",
    productCategory: "Drinks",
    barcode: "6131234567897",
    blinkPrice: 40,
    currentPrice: 45,
    suggestedPrice: 42,
    status: "pending",
    deviation: 5,
    submittedAt: Date.now() - 5400000,
  },
];

export function derivePricingStats(suggestions: PriceSuggestion[]) {
  const pending = suggestions.filter((s) => s.status === "pending");
  const accepted = suggestions.filter((s) => s.status === "accepted");
  const rejected = suggestions.filter((s) => s.status === "rejected");
  const overTolerance = suggestions.filter((s) => Math.abs(s.deviation) > 20);
  return {
    total: suggestions.length,
    pending: pending.length,
    accepted: accepted.length,
    rejected: rejected.length,
    overTolerance: overTolerance.length,
    avgDeviation: suggestions.length
      ? (suggestions.reduce((a, s) => a + Math.abs(s.deviation), 0) / suggestions.length).toFixed(1)
      : "0.0",
  };
}
